[build]
  command = "npm run build"
  publish = ".next"
  # Asegura Node 20 y apaga telemetría si quieres
  [build.environment]
    NODE_VERSION = "20"
    NEXT_TELEMETRY_DISABLED = "1"

# Runtime oficial de Next.js en Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"
